version: "3.7"

services:

  node:
    build:
      context: ./docker
    command: sh -c "tail -f /dev/null"
    working_dir: /app
    volumes:
      - ./:/app
    
  bot:
    build:
      context: ./docker
    command: sh -c "node index.js"
    working_dir: /app
    volumes:
      - ./:/app